# Insurance Claim Fraud Detection

In [35]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error ,r2_score
import warnings
warnings.filterwarnings('ignore')

In [36]:
df_auto=pd.read_csv('Automobile_insurance_fraud.csv')

In [37]:
df_auto

,328,48,521585,17-10-2014,OH,250/500,1000,1406.91,0,466132,...,2,YES.1,71610,6510,13020,52080,Saab,92x,2004,Y
0,228,42,342868,27-06-2006,IN,250/500,2000,1197.22,5000000,468176,...,0,?,5070,780,780,3510,Mercedes,E400,2007,Y
1,134,29,687698,06-09-2000,OH,100/300,2000,1413.14,5000000,430632,...,3,NO,34650,7700,3850,23100,Dodge,RAM,2007,N
2,256,41,227811,25-05-1990,IL,250/500,2000,1415.74,6000000,608117,...,2,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y
3,228,44,367455,06-06-2014,IL,500/1000,1000,1583.91,6000000,610706,...,1,NO,6500,1300,650,4550,Accura,RSX,2009,N
4,256,39,104594,12-10-2006,OH,250/500,1000,1351.10,0,478456,...,2,NO,64100,6410,6410,51280,Saab,95,2003,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,3,38,941851,16-07-1991,OH,500/1000,1000,1310.80,0,431289,...,1,?,87200,17440,8720,61040,Honda,Accord,2006,N
995,285,41,186934,05-01-2014,IL,100/300,1000,1436.79,0,608177,...,3,?,108480,18080,18080,72320,Volkswagen,Passat,2015,N
996,130,34,918516,17-02-2003,OH,250/500,500,1383.49,3000000,442797,...,3,YES,67500,7500,7500,52500,Suburu,Impreza,1996,N
997,458,62,533940,18-11-2011,IL,500/1000,2000,1356.92,5000000,441714,...,1,YES,46980,5220,5220,36540,Audi,A5,1998,N
998,456,60,556080,11-11-1996,OH,250/500,1000,766.19,0,612260,...,3,?,5060,460,920,3680,Mercedes,E400,2007,N

In [38]:
df_auto.columns

Index(['328', '48', '521585', '17-10-2014', 'OH', '250/500', '1000', '1406.91',
       '0', '466132', 'MALE', 'MD', 'craft-repair', 'sleeping', 'husband',
       '53300', '0.1', '25-01-2015', 'Single Vehicle Collision',
       'Side Collision', 'Major Damage', 'Police', 'SC', 'Columbus',
       '9935 4th Drive', '5', '1', 'YES', '1.1', '2', 'YES.1', '71610', '6510',
       '13020', '52080', 'Saab', '92x', '2004', 'Y'],
      dtype='object')

In [39]:
print(len(df_auto.columns))

39

In [40]:
column_names = [
    'months_as_customer',
    'age',
    'policy_number',
    'policy_bind_date',
    'policy_state',
    'policy_csi',
    'policy_deductable',
    'policy_annual_premium',
    'umbrella_limit',
    'insured_zip',
    'insured_sex',
    'insured_education_level',
    'insured_occupation',
    'insured_hobbies',
    'insured_relationship',
    'capital-gains',
    'capital-loss',
    'incident_date',
    'incident_type',
    'collision_type',
    'incident_severity',
    'authorities_contracted',
    'incident_state',
    'incident_city',
    'incident_location',
    'incident_hour_of_the_day',
    'number_of_vehicles_involved',
    'property_damage',
    'bodily_injuries',
    'witenesses',
    'police_report_available',
    'total_claim_amount',
    'injury_claim',
    'property_claim',
    'vehicle_claim',
    'auto_make',
    'auto_model',
    'auto_year',
    'fraud_reported'
]

In [41]:
print(len(column_names))

39

In [42]:
df_auto.columns = column_names

In [43]:
df_auto

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csi,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,witenesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported
0,228,42,342868,27-06-2006,IN,250/500,2000,1197.22,5000000,468176,...,0,?,5070,780,780,3510,Mercedes,E400,2007,Y
1,134,29,687698,06-09-2000,OH,100/300,2000,1413.14,5000000,430632,...,3,NO,34650,7700,3850,23100,Dodge,RAM,2007,N
2,256,41,227811,25-05-1990,IL,250/500,2000,1415.74,6000000,608117,...,2,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y
3,228,44,367455,06-06-2014,IL,500/1000,1000,1583.91,6000000,610706,...,1,NO,6500,1300,650,4550,Accura,RSX,2009,N
4,256,39,104594,12-10-2006,OH,250/500,1000,1351.10,0,478456,...,2,NO,64100,6410,6410,51280,Saab,95,2003,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,3,38,941851,16-07-1991,OH,500/1000,1000,1310.80,0,431289,...,1,?,87200,17440,8720,61040,Honda,Accord,2006,N
995,285,41,186934,05-01-2014,IL,100/300,1000,1436.79,0,608177,...,3,?,108480,18080,18080,72320,Volkswagen,Passat,2015,N
996,130,34,918516,17-02-2003,OH,250/500,500,1383.49,3000000,442797,...,3,YES,67500,7500,7500,52500,Suburu,Impreza,1996,N
997,458,62,533940,18-11-2011,IL,500/1000,2000,1356.92,5000000,441714,...,1,YES,46980,5220,5220,36540,Audi,A5,1998,N
998,456,60,556080,11-11-1996,OH,250/500,1000,766.19,0,612260,...,3,?,5060,460,920,3680,Mercedes,E400,2007,N

In [44]:
label_encoder = LabelEncoder()

In [45]:
for column in df_auto.columns:
    if df_auto[column].dtype == 'object':
        df_auto[column] = label_encoder.fit_transform(df_auto[column])

In [46]:
df_auto

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csi,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,witenesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported
0,228,42,342868,820,1,1,2000,1197.22,5000000,468176,...,0,0,5070,780,780,3510,8,12,2007,1
1,134,29,687698,186,2,0,2000,1413.14,5000000,430632,...,3,1,34650,7700,3850,23100,4,30,2007,0
2,256,41,227811,765,0,1,2000,1415.74,6000000,608117,...,2,1,63400,6340,6340,50720,3,34,2014,1
3,228,44,367455,181,0,2,1000,1583.91,6000000,610706,...,1,1,6500,1300,650,4550,0,31,2009,0
4,256,39,104594,385,2,1,1000,1351.10,0,478456,...,2,1,64100,6410,6410,51280,10,3,2003,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,3,38,941851,487,2,2,1000,1310.80,0,431289,...,1,0,87200,17440,8720,61040,6,6,2006,0
995,285,41,186934,129,0,0,1000,1436.79,0,608177,...,3,0,108480,18080,18080,72320,13,28,2015,0
996,130,34,918516,509,2,1,500,1383.49,3000000,442797,...,3,2,67500,7500,7500,52500,11,19,1996,0
997,458,62,533940,572,0,2,2000,1356.92,5000000,441714,...,1,2,46980,5220,5220,36540,1,5,1998,0
998,456,60,556080,359,2,1,1000,766.19,0,612260,...,3,0,5060,460,920,3680,8,12,2007,0

In [47]:
x = df_auto.iloc[:,0:-1] #feature variable

In [48]:
x

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csi,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,bodily_injuries,witenesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year
0,228,42,342868,820,1,1,2000,1197.22,5000000,468176,...,0,0,0,5070,780,780,3510,8,12,2007
1,134,29,687698,186,2,0,2000,1413.14,5000000,430632,...,2,3,1,34650,7700,3850,23100,4,30,2007
2,256,41,227811,765,0,1,2000,1415.74,6000000,608117,...,1,2,1,63400,6340,6340,50720,3,34,2014
3,228,44,367455,181,0,2,1000,1583.91,6000000,610706,...,0,1,1,6500,1300,650,4550,0,31,2009
4,256,39,104594,385,2,1,1000,1351.10,0,478456,...,0,2,1,64100,6410,6410,51280,10,3,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,3,38,941851,487,2,2,1000,1310.80,0,431289,...,0,1,0,87200,17440,8720,61040,6,6,2006
995,285,41,186934,129,0,0,1000,1436.79,0,608177,...,2,3,0,108480,18080,18080,72320,13,28,2015
996,130,34,918516,509,2,1,500,1383.49,3000000,442797,...,2,3,2,67500,7500,7500,52500,11,19,1996
997,458,62,533940,572,0,2,2000,1356.92,5000000,441714,...,0,1,2,46980,5220,5220,36540,1,5,1998
998,456,60,556080,359,2,1,1000,766.19,0,612260,...,0,3,0,5060,460,920,3680,8,12,2007

In [49]:
y = df_auto.iloc[:,-1] #target variable

In [50]:
y

0      1
1      0
2      1
3      0
4      1
      ..
994    0
995    0
996    0
997    0
998    0
Name: fraud_reported, Length: 999, dtype: int32

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import GridSearchCV

In [52]:
LR = LinearRegression()

In [53]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [54]:
LR.fit(X_train,y_train)

LinearRegression()

In [55]:
pred_y = LR.predict(X_test)

In [56]:
MSE = mean_squared_error(y_test,pred_y)

In [57]:
print("MSE :: ",round(MSE,2))

MSE ::  0.17

Hyperparameter tuning

In [58]:
model_max = LinearRegression()

In [59]:
param_grids_max = {
    'fit_intercept': [True, False]
}

In [60]:
grid_search_max = GridSearchCV(model_max,param_grids_max , cv=5, scoring='neg_mean_squared_error')

In [61]:
grid_search_max.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LinearRegression(),
             param_grid={'fit_intercept': [True, False]},
             scoring='neg_mean_squared_error')

In [62]:
best_model_max = grid_search_max.best_estimator_
best_params_max = grid_search_max.best_params_

In [63]:
print("Best hyperparameters:", best_params_max)

Best hyperparameters: {'fit_intercept': False}

In [64]:
best_model_max.fit(X_train, y_train)

LinearRegression(fit_intercept=False)

In [65]:
pred_y_max = best_model_max.predict(X_test)

In [66]:
best_score_max = grid_search_max.best_score_
print("Best score:", best_score_max)

Best score: -0.16390083869163996

In [67]:
positive_mse_max = -best_score_max

In [68]:
print("Positive mean squared error:", positive_mse_max)

Positive mean squared error: 0.16390083869163996